AWSTemplateFormatVersion: 2010-09-09

Description: This template creates an EC2 instance which enables SSH connection. # This is a comment

Resources:
  YascoCFInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02354e95b39ca8dec
      InstanceType: t2.micro
      KeyName: yasco-cfdemo-kp
      SecurityGroups:
        - yasco-cfdemo-sg
      Tags:
        - Key: Name
          Value: yasco-cf-instance
      